### ISSUE TITLE
Possibility of reading the bluetooth audio 

### ISSUE THREAD

**Issue by sysadminpower2019** [nicsure/TD-H3-Engineering#10]
Hello,

would it be possible in the future to allow the bluetooth audio to be transmitted to a computer and piped into a com port. that would be great for something like direwolf

**Comment by sysadminpower2019** [comment]
@nicsure is this possible either via an app or some other use of bluetooth as a TNC

**Comment by nicsure** [comment]
No

**Comment by sysadminpower2019** [comment]
doesnt the official windows application already allow some version of this?

On Saturday, November 16, 2024, nicsure ***@***.***> wrote:
> Closed #10 as completed.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci3.googleusercontent.com/meips/ADKq_NZf4e1HY5y5Vjr5sN478InGPdUh8NR2OuoVrz4jLQwopeoalgP0VdCKL-eyACnr1C6DHe6CC5inqZJ4-iX9e8pIl2gSzKVIMH0vQYmQ8KGujE8ofH9R6G-XM6w3-oyjMF_dhiqV9PELiQdOQ47k_HfHkyHqgTiG6_PX-BcZwbw_-BGMoF9SzBgEHZwqbLYCbumFdzeNxMLaVm5C9tFOI0_5FomNpcpvoRiRrdCLwG0JpC7jnAXxJKOsL-DCh6djesDP8gWDkOEsr3xU8j--qA=s0-d-e1-ft#https://github.com/notifications/beacon/AJWXABRPW5EDPT5WPSVIMSD2A3GJ5A5CNFSM6AAAAABMFG3HWKWGG33NNVSW45C7OR4XAZNWJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XKUY3PNVWWK3TUL5UWJTYAAAAAHEJNMLDQ.gif>Message
ID: ***@***.***>

**Comment by nicsure** [comment]
NO IT IS NOT POSSIBLE!
